quarkus:
  datasource:
    db-kind: postgresql
    devservices:
      volumes:
        "/tmp/test/data": /var/lib/postgresql/data
  hibernate-orm:
    database:
      generation: none
  flyway:
    migrate-at-start: true
